name: Setup Rust Toolchain

on:
  workflow_call:
    inputs:
      rust-version:
        default: '1.86'
        type: string
        required: false
      cache-key-suffix:
        default: ''
        type: string
        required: false
    outputs:
      rust-version:
        value: ${{ steps.rust-info.outputs.version }}

jobs:
  setup-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git clang libssl-dev llvm libudev-dev protobuf-compiler

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust-version }}
          default: true
          override: true

      - name: Add WASM target and rust-src
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-${{ inputs.rust-version }}-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Get Rust info
        id: rust-info
        run: echo "version=$(rustc --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
